ycustomhost = "ting-employee.cpxrtodkrhyv.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "12345678"
customdb = "employee"
custombucket = "tingshuxuan-bucket"
customregion = "us-east-1"
